# Generated by Django 6.0.4 on 2026-04-29 21:46

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('categories', models.JSONField(default=list)),
                ('country_label', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=10)),
                ('country_flag', models.CharField(max_length=10)),
                ('country_region', models.CharField(max_length=255)),
                ('country_lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('country_lng', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city_lat', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('city_lng', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('guest_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('room_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('bathroom_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('images', models.JSONField(default=list)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', '-created_at'], name='listing_lis_owner_i_4b8a60_idx'), models.Index(fields=['country_code', 'city_name'], name='listing_lis_country_031fa2_idx'), models.Index(fields=['price'], name='listing_lis_price_11ce52_idx'), models.Index(fields=['-created_at'], name='listing_lis_created_0f9fee_idx')],
            },
        ),
    ]
