# Generated by Django 6.0.4 on 2026-05-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Annonce', 'verbose_name_plural': 'Annonces'},
        ),
    ]
